In [4]:
import pandas as pd

bond = pd.read_csv(r"C:\Users\Preeti\Desktop\Preeti\Christ\Excel files (python)\jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [6]:
# Set Film as index
bond = bond.set_index("Film")
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [7]:
# Reset back to default integer index
bond = bond.reset_index()
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [8]:
bond = bond.set_index(["Film", "Year"])
bond

,,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,Year,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [10]:
bond = bond.reset_index()
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [11]:
# First row
bond.iloc[0]
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [12]:
# First five rows
bond.iloc[0:5]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [13]:
# Non‑contiguous rows
bond.iloc[[0, 3, 10]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN

In [14]:
# First row, first 3 columns
bond.iloc[0, 0:3]

Film           Dr. No
Year             1962
Actor    Sean Connery
Name: 0, dtype: object

In [25]:
# First 3 rows, Year and Box Office columns (by position)
bond.iloc[0:3, [1, 4]]

                              Actor  Budget
Film
Dr. No                 Sean Connery     7.0
From Russia with Love  Sean Connery    12.6
Goldfinger             Sean Connery    18.6

In [27]:

# Single movie
bond.loc["Skyfall"]

Year                         2012
Actor                Daniel Craig
Director               Sam Mendes
Box Office                  943.5
Budget                      170.2
Bond Actor Salary            14.5
Name: Skyfall, dtype: object

In [28]:
# Multiple movies
bond.loc[["Skyfall", "Spectre"]]

         Year         Actor    Director  Box Office  Budget  Bond Actor Salary
Film
Skyfall  2012  Daniel Craig  Sam Mendes       943.5   170.2               14.5
Spectre  2015  Daniel Craig  Sam Mendes       726.7   206.3               30.0

In [29]:
# Rows and specific columns
bond.loc["Skyfall", ["Year", "Actor", "Box Office"]]

Year                  2012
Actor         Daniel Craig
Box Office           943.5
Name: Skyfall, dtype: object

In [30]:
# loc[row_labels, column_labels]
bond.loc["Skyfall", "Box Office"]
bond.loc[["Skyfall", "Spectre"], ["Year", "Box Office"]]

         Year  Box Office
Film
Skyfall  2012       943.5
Spectre  2015       726.7

In [31]:
# iloc[row_positions, column_positions]
bond.iloc[0, 4]          # first row, Box Office
bond.iloc[0:3, [1, 4]]   # first 3 rows, Year & Box Office

                              Actor  Budget
Film
Dr. No                 Sean Connery     7.0
From Russia with Love  Sean Connery    12.6
Goldfinger             Sean Connery    18.6

In [41]:
# Change Skyfall budget
bond.loc["Skyfall", "Budget"] = 180.0
# By position
bond.iloc[0, 4] = 450.0    # change first row Box Office

In [38]:
# Replace all NaN salaries with 0
bond["Bond Actor Salary"] = bond["Bond Actor Salary"].fillna(0)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,450.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,0.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,0.0
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,0.0
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,0.0
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,0.0
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,0.0
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,0.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,180.0,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [42]:
# Increase Daniel Craig salaries by 10
mask = bond["Actor"] == "Daniel Craig"
bond.loc[mask, "Bond Actor Salary"] = bond.loc[mask, "Bond Actor Salary"] + 10

In [49]:
# Rename specific columns
bond = bond.rename(columns={"Box Office": "BoxOffice", "Bond Actor Salary": "BondSalary"})

In [50]:
bond

,Year,Actor,Director,BoxOffice,Budget,BondSalary
Film,,,,,,
Dr No,1962,Sean Connery,Terence Young,448.8,450.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,0.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,0.0
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,0.0
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,0.0
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,0.0
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,0.0
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,0.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,13.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,18.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,180.0,24.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,40.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,35.0

In [51]:
# Rename index values (if Film is index)
bond = bond.rename(index={"Dr. No": "Dr No"})
bond

,Year,Actor,Director,BoxOffice,Budget,BondSalary
Film,,,,,,
Dr No,1962,Sean Connery,Terence Young,448.8,450.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,0.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,0.0
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,0.0
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,0.0
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,0.0
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,0.0
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,0.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,13.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,18.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,180.0,24.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,40.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,35.0

In [52]:
#replace all column names at once
bond.columns = ["Film", "Year", "Actor", "Director", "BoxOffice", "Budget", "BondSalary"]

ValueError: Length mismatch: Expected axis has 6 elements, new values have 7 elements

In [53]:
bond

,Year,Actor,Director,BoxOffice,Budget,BondSalary
Film,,,,,,
Dr No,1962,Sean Connery,Terence Young,448.8,450.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,0.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,0.0
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,0.0
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,0.0
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,0.0
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,0.0
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,0.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,13.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,18.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,180.0,24.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,40.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,35.0

In [55]:
# Drop columns
bond = bond.drop(columns=["BondSalary"])

In [56]:
bond

,Year,Actor,Director,BoxOffice,Budget
Film,,,,,
Dr No,1962,Sean Connery,Terence Young,448.8,450.0
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,180.0
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0

In [59]:
# Drop rows by index label
bond = bond.drop(index=["Skyfall"])

In [60]:
bond

,Year,Actor,Director,BoxOffice,Budget
Film,,,,,
Dr No,1962,Sean Connery,Terence Young,448.8,450.0
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0

In [61]:
# Drop rows by position
bond = bond.drop(index=bond.index[0:3])
bond

,Year,Actor,Director,BoxOffice,Budget
Film,,,,,
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0

In [63]:
# 3 highest box office films
bond.nlargest(3, "BoxOffice")

                Year         Actor            Director  BoxOffice  Budget
Film
Thunderball     1965  Sean Connery       Terence Young      848.1    41.9
No Time to Die  2021  Daniel Craig  Cary Joji Fukunaga      774.2   301.0
Spectre         2015  Daniel Craig          Sam Mendes      726.7   206.3

In [64]:
# 5 smallest budgets
bond.nsmallest(5, "Budget")

,Year,Actor,Director,BoxOffice,Budget
Film,,,,,
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9

In [67]:
# Keep only films after 2000, others become NaN
after_2000 = bond.where(bond["Year"] > 2000)
after_2000

,Year,Actor,Director,BoxOffice,Budget
Film,,,,,
Thunderball,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN
A View to a Kill,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN
Licence to Kill,NaN,NaN,NaN,NaN,NaN
GoldenEye,NaN,NaN,NaN,NaN,NaN
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN
Die Another Day,2002.0,Pierce Brosnan,Lee Tamahori,465.4,154.2
Casino Royale,2006.0,Daniel Craig,Martin Campbell,581.5,145.3
Quantum of Solace,2008.0,Daniel Craig,Marc Forster,514.2,181.4
Spectre,2015.0,Daniel Craig,Sam Mendes,726.7,206.3
No Time to Die,2021.0,Daniel Craig,Cary Joji Fukunaga,774.2,301.0

In [68]:
# Standard boolean filtering (dropping rows that do not match)
only_craig = bond[bond["Actor"] == "Daniel Craig"]
only_craig

                   Year         Actor            Director  BoxOffice  Budget
Film
Casino Royale      2006  Daniel Craig     Martin Campbell      581.5   145.3
Quantum of Solace  2008  Daniel Craig        Marc Forster      514.2   181.4
Spectre            2015  Daniel Craig          Sam Mendes      726.7   206.3
No Time to Die     2021  Daniel Craig  Cary Joji Fukunaga      774.2   301.0

In [71]:
# Example: profit = Box Office - Budget
def profit(row):
    return row["BoxOffice"] - row["Budget"]

bond["Profit"] = bond.apply(profit, axis="columns")
bond

,Year,Actor,Director,BoxOffice,Budget,Profit
Film,,,,,,
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,806.2
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,230.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,454.3
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,254.2
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,407.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,429.5
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,306.3
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,487.9
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,443.5
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,389.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,294.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,319.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,220.7
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,244.7
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,194.2
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,441.6
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,329.3
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,281.2
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,311.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,436.2
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,332.8
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,520.4
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,473.2